COMPANY_NAMES = {
    'JNJ': 'Johnson & Johnson',
    'PG': 'Procter & Gamble',
    'KO': 'Coca-Cola',
    'MCD': 'McDonald\'s',
    'O': 'Realty Income',
    'JPM': 'JPMorgan Chase',
    'BAC': 'Bank of America',
    'BLK': 'BlackRock',
    'AVGO': 'Broadcom Inc.',
    'TXN': 'Texas Instruments',
    'XOM': 'Exxon Mobil',
    'CVX': 'Chevron',
    'MMM': '3M Company',
    'ABBV': 'AbbVie',
    'AMT': 'American Tower',
    'CCI': 'Crown Castle',
    'MSFT': 'Microsoft',
    'AAPL': 'Apple',
    'LOW': 'Lowe\'s',
    'HD': 'Home Depot',
    'PM': 'Philip Morris',
    'MO': 'Altria Group',
    'KHC': 'Kraft Heinz',
    'PEP': 'PepsiCo',
    'WMT': 'Walmart',
    'TGT': 'Target',
    'NEE': 'NextEra Energy',
    'SO': 'Southern Company',
    'DUK': 'Duke Energy',
    'IBM': 'International Business Machines',
    'VZ': 'Verizon'
}